# Use a builder container to install the dependencies,
# then switch to a more lightweight interpreter
FROM python:3.9 AS builder

COPY requirements.txt .
RUN pip install --user -r requirements.txt


# Setup the final container
FROM python:3.9-slim
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local:$PATH

WORKDIR /gmsh

VOLUME /gmsh/config

# default database volume in case nothing usable is provided
VOLUME /db
# and default env variables pointing there
ENV DB_LOCATION sqlite:////db/gmsh.sqlite
ENV DB_PLAYGROUND_LOCATION sqlite:////db/playground.sqlite

# This will become relevant if I add a web interface to my bot
# ENV SERVER_PORT 8080
# EXPOSE $SERVER_PORT

COPY ./logging.yaml .

# copy the code and default configuration
COPY ./gmsh ./gmsh
COPY ./ezconf ./ezconf

CMD [ "python", "-m", "gmsh" ]